// 200 French words for the "mot du jour" card.
// Each entry: { word, pos, translation, definition }
// pos values: n = noun, v = verb, adj = adjective, adv = adverb, expr = expression

const mots = [
  { word: "flâner", pos: "v.", translation: "to wander aimlessly", definition: "To stroll without purpose or destination, often through a city, purely for the pleasure of it." },
  { word: "dépaysement", pos: "n.", translation: "disorientation of a new place", definition: "The strange, often pleasant feeling of being somewhere unfamiliar, out of your usual context." },
  { word: "retrouvailles", pos: "n.", translation: "reunion", definition: "The joy of seeing someone again after a long time apart." },
  { word: "chaleureux", pos: "adj.", translation: "warm, welcoming", definition: "Describes a person or place that feels friendly and inviting." },
  { word: "bricoler", pos: "v.", translation: "to tinker, DIY", definition: "To fix or build things yourself, often with makeshift tools or methods." },
  { word: "quotidien", pos: "n./adj.", translation: "everyday life; daily", definition: "The ordinary routine of day-to-day living." },
  { word: "chuchoter", pos: "v.", translation: "to whisper", definition: "To speak very softly, barely audible." },
  { word: "orage", pos: "n.", translation: "thunderstorm", definition: "A storm with thunder, lightning, and heavy rain." },
  { word: "aube", pos: "n.", translation: "dawn", definition: "The first light of day, before sunrise." },
  { word: "crépuscule", pos: "n.", translation: "dusk, twilight", definition: "The soft light after sunset, before full darkness." },
  { word: "ronronner", pos: "v.", translation: "to purr", definition: "The sound a contented cat makes." },
  { word: "boulanger", pos: "n.", translation: "baker", definition: "A person who bakes and sells bread." },
  { word: "menuisier", pos: "n.", translation: "carpenter", definition: "A craftsman who works with wood, especially building furniture or fittings." },
  { word: "infirmière", pos: "n.", translation: "nurse (f.)", definition: "A medical professional who cares for patients." },
  { word: "pompier", pos: "n.", translation: "firefighter", definition: "A person trained to put out fires and handle emergencies." },
  { word: "vétérinaire", pos: "n.", translation: "veterinarian", definition: "A doctor for animals." },
  { word: "bricoleur", pos: "n.", translation: "handyman", definition: "Someone skilled at fixing and building things themselves." },
  { word: "voisinage", pos: "n.", translation: "neighborhood", definition: "The area and community immediately around where you live." },
  { word: "chez-soi", pos: "n.", translation: "one's own home", definition: "The specific comfort and belonging of being in your own place." },
  { word: "cocon", pos: "n.", translation: "cocoon", definition: "A protective wrapping; used figuratively for a cozy, sheltered space." },
  { word: "papillon", pos: "n.", translation: "butterfly", definition: "A flying insect known for its colorful wings." },
  { word: "hérisson", pos: "n.", translation: "hedgehog", definition: "A small spiny mammal that curls into a ball when threatened." },
  { word: "écureuil", pos: "n.", translation: "squirrel", definition: "A small bushy-tailed rodent that often stores nuts." },
  { word: "libellule", pos: "n.", translation: "dragonfly", definition: "A slender flying insect with long, transparent wings, often seen near water." },
  { word: "escargot", pos: "n.", translation: "snail", definition: "A slow-moving mollusk with a spiral shell." },
  { word: "grenouille", pos: "n.", translation: "frog", definition: "A small amphibian known for jumping and croaking." },
  { word: "chouette", pos: "n./adj.", translation: "owl; also 'cool/nice'", definition: "A nocturnal bird of prey; informally used to mean something great." },
  { word: "faucon", pos: "n.", translation: "falcon", definition: "A fast, sharp-eyed bird of prey." },
  { word: "renard", pos: "n.", translation: "fox", definition: "A cunning, medium-sized wild canine." },
  { word: "colline", pos: "n.", translation: "hill", definition: "A raised area of land, smaller than a mountain." },
  { word: "ruisseau", pos: "n.", translation: "stream", definition: "A small, narrow flow of water, smaller than a river." },
  { word: "falaise", pos: "n.", translation: "cliff", definition: "A steep rock face, often by the sea." },
  { word: "brouillard", pos: "n.", translation: "fog", definition: "Thick mist that reduces visibility near the ground." },
  { word: "givre", pos: "n.", translation: "frost", definition: "A thin layer of ice crystals forming on cold surfaces." },
  { word: "averse", pos: "n.", translation: "sudden rain shower", definition: "A brief, often heavy burst of rain." },
  { word: "embruns", pos: "n.", translation: "sea spray", definition: "Fine mist of seawater blown off the tops of waves." },
  { word: "marée", pos: "n.", translation: "tide", definition: "The regular rise and fall of the sea's level." },
  { word: "horizon", pos: "n.", translation: "horizon", definition: "The line where the earth or sea meets the sky." },
  { word: "vertige", pos: "n.", translation: "dizziness, vertigo", definition: "A spinning sensation, often from heights or sudden movement." },
  { word: "frissonner", pos: "v.", translation: "to shiver", definition: "To tremble slightly, from cold or emotion." },
  { word: "soupirer", pos: "v.", translation: "to sigh", definition: "To let out a long breath, often from relief, sadness, or longing." },
  { word: "s'épanouir", pos: "v.", translation: "to blossom, flourish", definition: "To grow and thrive, becoming fully oneself — of people or plants." },
  { word: "apaiser", pos: "v.", translation: "to soothe, calm", definition: "To bring peace or relief to someone distressed." },
  { word: "réconfort", pos: "n.", translation: "comfort", definition: "A feeling of relief or consolation." },
  { word: "tendresse", pos: "n.", translation: "tenderness", definition: "Gentle, affectionate warmth toward someone." },
  { word: "malaise", pos: "n.", translation: "unease, discomfort", definition: "A vague feeling that something is wrong." },
  { word: "insouciant", pos: "adj.", translation: "carefree", definition: "Free from worry or concern, light-hearted." },
  { word: "morose", pos: "adj.", translation: "gloomy, sullen", definition: "In a low, joyless mood." },
  { word: "espiègle", pos: "adj.", translation: "mischievous", definition: "Playfully naughty, full of harmless pranks." },
  { word: "farfelu", pos: "adj.", translation: "quirky, whimsical", definition: "Odd or eccentric in a charming, unpredictable way." },
  { word: "rêvasser", pos: "v.", translation: "to daydream", definition: "To let one's mind wander idly instead of focusing." },
  { word: "vagabonder", pos: "v.", translation: "to roam, wander", definition: "To travel with no fixed destination." },
  { word: "s'évader", pos: "v.", translation: "to escape", definition: "To break free, literally or mentally, from confinement or routine." },
  { word: "gaspiller", pos: "v.", translation: "to waste", definition: "To use something carelessly, without value or purpose." },
  { word: "économiser", pos: "v.", translation: "to save (money/resources)", definition: "To set something aside rather than spend or use it." },
  { word: "emprunter", pos: "v.", translation: "to borrow", definition: "To take something temporarily, intending to return it." },
  { word: "prêter", pos: "v.", translation: "to lend", definition: "To give something temporarily, expecting it back." },
  { word: "négocier", pos: "v.", translation: "to negotiate", definition: "To discuss terms in order to reach an agreement." },
  { word: "s'entêter", pos: "v.", translation: "to be stubborn about something", definition: "To insist on one's own way despite objections." },
  { word: "céder", pos: "v.", translation: "to give in, yield", definition: "To stop resisting and allow something." },
  { word: "avouer", pos: "v.", translation: "to admit, confess", definition: "To acknowledge something, often something difficult to say." },
  { word: "se méfier", pos: "v.", translation: "to be wary, distrust", definition: "To be cautious of someone or something." },
  { word: "chuchotement", pos: "n.", translation: "a whisper", definition: "The sound or act of speaking very quietly." },
  { word: "vacarme", pos: "n.", translation: "loud noise, racket", definition: "A chaotic burst of loud, confused sound." },
  { word: "silence", pos: "n.", translation: "silence", definition: "The complete absence of sound." },
  { word: "étincelle", pos: "n.", translation: "spark", definition: "A tiny flash of light or fire; also used figuratively for a spark of inspiration." },
  { word: "lueur", pos: "n.", translation: "glow, faint light", definition: "A soft, dim light, often at a distance." },
  { word: "ombre", pos: "n.", translation: "shadow", definition: "The dark shape cast when light is blocked." },
  { word: "reflet", pos: "n.", translation: "reflection", definition: "An image mirrored back, as in water or glass." },
  { word: "mirage", pos: "n.", translation: "mirage", definition: "An optical illusion, often of water, caused by heat." },
  { word: "songe", pos: "n.", translation: "dream (literary)", definition: "A dream, especially in a poetic or old-fashioned sense." },
  { word: "cauchemar", pos: "n.", translation: "nightmare", definition: "A frightening or unpleasant dream." },
  { word: "sieste", pos: "n.", translation: "nap", definition: "A short sleep, typically in the afternoon." },
  { word: "réveil", pos: "n.", translation: "waking up; alarm clock", definition: "The moment of waking, or the device that causes it." },
  { word: "paresse", pos: "n.", translation: "laziness", definition: "A reluctance to work or exert effort." },
  { word: "acharnement", pos: "n.", translation: "relentlessness, fierce determination", definition: "Persisting at something with great, almost fierce effort." },
  { word: "persévérance", pos: "n.", translation: "perseverance", definition: "Continued effort despite difficulty." },
  { word: "audace", pos: "n.", translation: "boldness, daring", definition: "Willingness to take risks or act with confidence." },
  { word: "prudence", pos: "n.", translation: "caution", definition: "Careful avoidance of risk." },
  { word: "sagesse", pos: "n.", translation: "wisdom", definition: "The quality of having good judgment from experience." },
  { word: "naïveté", pos: "n.", translation: "naivety", definition: "A lack of experience or worldly judgment, often innocent." },
  { word: "ruse", pos: "n.", translation: "cunning, trickery", definition: "A clever, sometimes deceptive strategy." },
  { word: "malice", pos: "n.", translation: "mischief, slyness", definition: "A playful or sly intent to tease or trick." },
  { word: "clairvoyance", pos: "n.", translation: "clear-sightedness", definition: "The ability to perceive things clearly and accurately." },
  { word: "entêtement", pos: "n.", translation: "stubbornness", definition: "A firm, sometimes unreasonable refusal to change one's mind." },
  { word: "générosité", pos: "n.", translation: "generosity", definition: "Willingness to give freely." },
  { word: "avarice", pos: "n.", translation: "greed", definition: "Excessive desire to keep wealth or resources for oneself." },
  { word: "convivialité", pos: "n.", translation: "conviviality, friendliness", definition: "A warm, sociable atmosphere among people." },
  { word: "solitude", pos: "n.", translation: "solitude", definition: "The state of being alone, not necessarily unhappily." },
  { word: "isolement", pos: "n.", translation: "isolation", definition: "Being cut off from others, often unwillingly." },
  { word: "appartenance", pos: "n.", translation: "belonging", definition: "The sense of being part of a group or place." },
  { word: "racines", pos: "n.", translation: "roots", definition: "One's origins or deep connections to a place or family." },
  { word: "héritage", pos: "n.", translation: "heritage, inheritance", definition: "What is passed down from previous generations." },
  { word: "artisan", pos: "n.", translation: "craftsman", definition: "A skilled worker who makes things by hand." },
  { word: "orfèvre", pos: "n.", translation: "goldsmith", definition: "A craftsman who works with gold and precious metals." },
  { word: "potier", pos: "n.", translation: "potter", definition: "A craftsman who shapes and fires clay into pottery." },
  { word: "vitrail", pos: "n.", translation: "stained glass window", definition: "A decorative window made of colored glass pieces." },
  { word: "fresque", pos: "n.", translation: "fresco, mural", definition: "A large painting made directly on a wall or ceiling." },
  { word: "sculpteur", pos: "n.", translation: "sculptor", definition: "An artist who shapes stone, wood, or metal into forms." },
  { word: "esquisse", pos: "n.", translation: "sketch", definition: "A rough, quick drawing, often a first draft." },
  { word: "chef-d'œuvre", pos: "n.", translation: "masterpiece", definition: "A work of outstanding skill, someone's finest achievement." },
  { word: "inachevé", pos: "adj.", translation: "unfinished", definition: "Not yet complete." },
  { word: "ébauche", pos: "n.", translation: "rough draft, outline", definition: "An early, incomplete version of a work." },
  { word: "improviser", pos: "v.", translation: "to improvise", definition: "To create or perform something without preparation." },
  { word: "répéter", pos: "v.", translation: "to rehearse; to repeat", definition: "To practice something, or to say/do it again." },
  { word: "orchestre", pos: "n.", translation: "orchestra", definition: "A large group of musicians playing together." },
  { word: "mélodie", pos: "n.", translation: "melody", definition: "A sequence of musical notes forming a tune." },
  { word: "cadence", pos: "n.", translation: "rhythm, cadence", definition: "A regular, repeated pattern of sound or movement." },
  { word: "harmonie", pos: "n.", translation: "harmony", definition: "A pleasing combination of sounds, colors, or ideas." },
  { word: "dissonance", pos: "n.", translation: "dissonance", definition: "A harsh, clashing combination of sounds; disagreement." },
  { word: "murmure", pos: "n.", translation: "murmur", definition: "A soft, low, continuous sound, like quiet talking or water." },
  { word: "grondement", pos: "n.", translation: "rumble", definition: "A deep, continuous rolling sound, like distant thunder." },
  { word: "éclat", pos: "n.", translation: "brightness, brilliance; burst", definition: "A vivid brightness or shine; also a sudden burst, as of laughter." },
  { word: "scintiller", pos: "v.", translation: "to sparkle, twinkle", definition: "To shine with quick flashes of light." },
  { word: "chatoyant", pos: "adj.", translation: "shimmering", definition: "Changing color or shine depending on the angle of light." },
  { word: "velouté", pos: "adj.", translation: "velvety, smooth", definition: "Soft and smooth to the touch or taste." },
  { word: "croustillant", pos: "adj.", translation: "crispy", definition: "Having a pleasing crunch, especially of food." },
  { word: "moelleux", pos: "adj.", translation: "soft, moist (of food)", definition: "Soft and tender, often describing baked goods." },
  { word: "acidulé", pos: "adj.", translation: "tangy, slightly sour", definition: "Having a pleasant, sharp sourness." },
  { word: "épicé", pos: "adj.", translation: "spicy", definition: "Having a strong, hot flavor from spices." },
  { word: "mijoter", pos: "v.", translation: "to simmer", definition: "To cook slowly over low heat." },
  { word: "assaisonner", pos: "v.", translation: "to season", definition: "To add salt, spices, or herbs to food." },
  { word: "gourmandise", pos: "n.", translation: "love of good food; a treat", definition: "A fondness for delicious food, or the treat itself." },
  { word: "terroir", pos: "n.", translation: "sense of place (in food/wine)", definition: "The specific environment — soil, climate, tradition — that gives local food or wine its character." },
  { word: "vendange", pos: "n.", translation: "grape harvest", definition: "The annual gathering of grapes for winemaking." },
  { word: "verger", pos: "n.", translation: "orchard", definition: "A piece of land planted with fruit trees." },
  { word: "potager", pos: "n.", translation: "vegetable garden", definition: "A garden grown for food, especially vegetables." },
  { word: "récolte", pos: "n.", translation: "harvest", definition: "The gathering of crops when ripe." },
  { word: "semer", pos: "v.", translation: "to sow", definition: "To plant seeds." },
  { word: "germer", pos: "v.", translation: "to sprout, germinate", definition: "For a seed to begin growing." },
  { word: "fleurir", pos: "v.", translation: "to bloom, flourish", definition: "To produce flowers; also used figuratively for thriving." },
  { word: "fanée", pos: "adj.", translation: "wilted", definition: "Faded and drooping, of a flower or plant." },
  { word: "feuillage", pos: "n.", translation: "foliage", definition: "The leaves of trees and plants collectively." },
  { word: "clairière", pos: "n.", translation: "clearing (in a forest)", definition: "An open space within a forest, free of trees." },
  { word: "sentier", pos: "n.", translation: "path, trail", definition: "A narrow track, often through nature." },
  { word: "carrefour", pos: "n.", translation: "crossroads", definition: "A point where roads or ideas meet." },
  { word: "impasse", pos: "n.", translation: "dead end", definition: "A street or situation with no way forward." },
  { word: "détour", pos: "n.", translation: "detour", definition: "An indirect route taken instead of the direct one." },
  { word: "raccourci", pos: "n.", translation: "shortcut", definition: "A quicker route or method than the usual one." },
  { word: "escale", pos: "n.", translation: "stopover", definition: "A brief stop during a longer journey." },
  { word: "périple", pos: "n.", translation: "long journey, odyssey", definition: "An extended trip, often eventful or adventurous." },
  { word: "errance", pos: "n.", translation: "wandering", definition: "The act of moving about without a fixed goal." },
  { word: "exil", pos: "n.", translation: "exile", definition: "Being forced or choosing to live away from one's homeland." },
  { word: "patrie", pos: "n.", translation: "homeland", definition: "One's native country, especially with emotional attachment." },
  { word: "frontière", pos: "n.", translation: "border", definition: "The line dividing two countries or regions." },
  { word: "métissage", pos: "n.", translation: "blending of cultures", definition: "The mixing of different cultural or ethnic backgrounds." },
  { word: "cosmopolite", pos: "adj.", translation: "cosmopolitan", definition: "Made up of, or comfortable among, many cultures." },
  { word: "citadin", pos: "n./adj.", translation: "city dweller; urban", definition: "A person who lives in a city, or relating to city life." },
  { word: "campagnard", pos: "n./adj.", translation: "country dweller; rural", definition: "A person who lives in the countryside, or relating to rural life." },
  { word: "hameau", pos: "n.", translation: "hamlet", definition: "A very small settlement, smaller than a village." },
  { word: "ruelle", pos: "n.", translation: "alley, narrow street", definition: "A small, narrow street, often between buildings." },
  { word: "place", pos: "n.", translation: "square (in a town)", definition: "An open public space in a town or city." },
  { word: "clocher", pos: "n.", translation: "bell tower", definition: "The tower of a church, usually holding bells." },
  { word: "grenier", pos: "n.", translation: "attic", definition: "The space directly under a roof, often used for storage." },
  { word: "cave", pos: "n.", translation: "cellar", definition: "An underground room, often for storage or wine." },
  { word: "seuil", pos: "n.", translation: "threshold, doorstep", definition: "The point of entry to a home; also a figurative turning point." },
  { word: "fenêtre", pos: "n.", translation: "window", definition: "An opening in a wall for light and air, usually glazed." },
  { word: "volet", pos: "n.", translation: "shutter", definition: "A hinged cover for a window, common on French houses." },
  { word: "cheminée", pos: "n.", translation: "fireplace, chimney", definition: "A structure for burning fire indoors, and its chimney." },
  { word: "bougie", pos: "n.", translation: "candle", definition: "A wax stick with a wick, burned for light." },
  { word: "veillée", pos: "n.", translation: "evening gathering", definition: "An evening spent together, often with storytelling or quiet activity." },
  { word: "berceuse", pos: "n.", translation: "lullaby", definition: "A soft song sung to help a child fall asleep." },
  { word: "enfance", pos: "n.", translation: "childhood", definition: "The period of being a child." },
  { word: "vieillesse", pos: "n.", translation: "old age", definition: "The later years of life." },
  { word: "aïeul", pos: "n.", translation: "ancestor, grandparent", definition: "A forebear, especially a grandparent." },
  { word: "cadet", pos: "n.", translation: "younger sibling", definition: "A younger brother or sister in a family." },
  { word: "aîné", pos: "n.", translation: "elder sibling", definition: "The oldest child in a family." },
  { word: "complicité", pos: "n.", translation: "closeness, being in on it together", definition: "A deep, easy understanding between people, as if sharing a secret." },
  { word: "confidence", pos: "n.", translation: "secret shared in trust", definition: "A private matter told to someone trusted." },
  { word: "fidélité", pos: "n.", translation: "loyalty, faithfulness", definition: "Steady, unwavering commitment to someone or something." },
  { word: "trahison", pos: "n.", translation: "betrayal", definition: "A break of trust or loyalty." },
  { word: "pardon", pos: "n.", translation: "forgiveness", definition: "Letting go of resentment toward someone." },
  { word: "regret", pos: "n.", translation: "regret", definition: "Sadness over something done or not done." },
  { word: "nostalgie", pos: "n.", translation: "nostalgia", definition: "A wistful longing for the past." },
  { word: "espoir", pos: "n.", translation: "hope", definition: "A feeling that something good may happen." },
  { word: "désinvolture", pos: "n.", translation: "casualness, offhandedness", definition: "A relaxed, unconcerned way of acting, sometimes bordering on careless." },
  { word: "flegme", pos: "n.", translation: "composure, coolness", definition: "Calm, unbothered self-control, even under pressure." },
  { word: "fougue", pos: "n.", translation: "fire, spiritedness", definition: "Passionate energy and enthusiasm." },
  { word: "élan", pos: "n.", translation: "momentum, drive", definition: "Enthusiastic energy propelling someone forward." },
  { word: "panache", pos: "n.", translation: "flair, panache", definition: "A stylish, confident way of doing something." },
  { word: "coup de foudre", pos: "expr.", translation: "love at first sight", definition: "Literally 'bolt of lightning' — an instant, powerful attraction." },
  { word: "avoir le cafard", pos: "expr.", translation: "to feel down, blue", definition: "Literally 'to have the cockroach' — a colorful way of saying you're feeling low." },
  { word: "il pleut des cordes", pos: "expr.", translation: "it's raining cats and dogs", definition: "Literally 'it's raining ropes' — used for very heavy rain." },
  { word: "poser un lapin", pos: "expr.", translation: "to stand someone up", definition: "Literally 'to put down a rabbit' — to not show up to a planned meeting." },
  { word: "bavarder", pos: "v.", translation: "to chat", definition: "To talk casually and at length with someone." },
  { word: "gribouiller", pos: "v.", translation: "to scribble", definition: "To write or draw quickly and messily." },
  { word: "étourdi", pos: "adj.", translation: "scatterbrained", definition: "Forgetful or absent-minded, easily distracted." },
  { word: "débrouillard", pos: "adj.", translation: "resourceful", definition: "Good at figuring things out and solving problems independently." },
  { word: "chaleur", pos: "n.", translation: "heat, warmth", definition: "High temperature; also warmth of feeling." },
  { word: "fraîcheur", pos: "n.", translation: "coolness, freshness", definition: "A pleasant, cool quality, of air, food, or ideas." },
  { word: "onde", pos: "n.", translation: "wave (physics), ripple", definition: "A wave, as of water, sound, or radio." },
  { word: "étoile filante", pos: "n.", translation: "shooting star", definition: "A meteor briefly streaking across the night sky." },
  { word: "voie lactée", pos: "n.", translation: "Milky Way", definition: "The galaxy that contains our solar system, visible as a band of light." },
  { word: "abîme", pos: "n.", translation: "abyss", definition: "A deep, seemingly bottomless chasm." },
  { word: "sommet", pos: "n.", translation: "summit, peak", definition: "The highest point of a mountain or achievement." },
  { word: "vallée", pos: "n.", translation: "valley", definition: "Low land between hills or mountains." },
  { word: "torrent", pos: "n.", translation: "torrent, rushing stream", definition: "A fast, powerful flow of water." },
  { word: "abriter", pos: "v.", translation: "to shelter", definition: "To provide protection or a place to stay." },
  { word: "s'installer", pos: "v.", translation: "to settle in", definition: "To make oneself comfortable or establish oneself somewhere." },
  { word: "déménager", pos: "v.", translation: "to move house", definition: "To relocate from one home to another." },
];

